# Generated by Django 4.1.7 on 2023-03-17 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0003_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='sobrenome',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
