# Generated by Django 4.1.7 on 2023-03-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0005_pedido_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='foto',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='foto',
            field=models.ImageField(default=1, upload_to='foto'),
            preserve_default=False,
        ),
    ]
